server:
  port: 8085



spring:
  # DB 연결
  datasource:
    # url: jdbc:oracle:thin:@localhost:1521/xe

    #url: jdbc:oracle:thin:@192.168.0.24:1522/xe

    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    # 접속을 위한 드라이버
    #driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: "music-app"
    password: musicapp